workflows:
  mycroft-volco-saliment:
    name: build Mycroft & Piper TTS environment
    environment:
      groups:
        - mycroft_deps
      python: "3.11"  # Use specific Python version compatible with Mycroft
    scripts:
      - name: Install System Dependencies
        script: |
          apt-get update
          apt-get install -y \
            python3-dev \
            build-essential \
            libffi-dev \
            portaudio19-dev \
            libjack-jackd2-dev \
            libssl-dev \
            libxml2-dev \
            libxslt1-dev \
            zlib1g-dev
      
      - name: Install Python dependencies
        script: |
          pip install --upgrade pip
          pip install wheel setuptools
          # Add your Mycroft/Piper specific dependencies here
          # pip install -r requirements.txt

      - name: Build project
        script: |
          echo "Add your build commands here"
          # python setup.py build
          # or your specific build commands

      - name: Run tests (if any)
        script: |
          echo "Add your test commands here"
          # python -m pytest tests/

    artifacts:
      - build/**/*.so
      - dist/**/*
      - *.whl

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true